services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
    networks:
      - app-network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client
    ports:
      - "3000:80" # Expose port 80 from NGINX as 3000 externally
    networks:
      - app-network

networks:
  app-network:
    driver: bridge